environment:
  sdk: ^3.9.0


name: request_repository
description: Dart package which manages the request.
publish_to: "none"
version: 1.0.0


dependencies:
  flutter:
    sdk: flutter
  uuid: ^4.5.1

  # Firebase
  cloud_firestore: ^6.0.0
  firebase_storage: ^13.0.1

  # Equatable for value comparison
  equatable: ^2.0.7

  # Custom Repository
  user_repository:
    path: ../user_repository

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true