name: myproject
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.7.2
  

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  fluentui_system_icons: ^1.1.273 # أيقونات فلوينت يو آي
  flutter_screenutil: ^5.0.0 # أبعاد شاشات بشكل مناسب
  cupertino_icons: ^1.0.8 
  flutter_native_splash: ^2.4.4 # native Screen Splash
  smooth_page_indicator: ^1.0.0 # مؤشر الصفحة السلس
  internet_connection_checker: ^3.0.1  # معرفة مستخدم تطبيق لديه انترنت او لا
  lottie: ^3.2.0  # إضافة انيميشن
  image_picker: ^1.1.2 # اختيار الصور من المعرض أو الكاميرا
  cached_network_image: ^3.2.3 # تحميل الصور من الانترنت مع التخزين المؤقت
  table_calendar: ^3.0.9 #مكتبة التقويم
  connectivity_plus: ^6.1.5 # إضافة للتحكم بالإنترنت
  logger: ^2.5.0 # إضافة لمعالجة الأخطاء بشكل أفضل
  readmore: ^3.0.0 # إضافة لعرض نصوص قابلة للقراءة مع خيار "اقرأ المزيد"
  excel: ^4.0.6 # قراءة وكتابة ملفات Excel
  file_picker: ^10.3.3  # اختيار الملفات من الجهاز
  path: ^1.8.3 # التعامل مع مسارات الملفات
  csv: ^5.0.2 # قراءة وكتابة ملفات CSV
  path_provider: ^2.1.1 # الحصول على مسارات الملفات
  shared_preferences: ^2.2.4 # تخزين البيانات محلياً
  share_plus: ^12.0.1  # مشاركة الملفات والنصوص
  intl: 0.20.2 # دعم اللغات والتنسيقات
  url_launcher: ^6.1.14  # فتح الروابط الخارجية
  flutter_dotenv: ^5.1.0 
  permission_handler: ^12.0.1  # طلب الأذونات من المستخدم
  syncfusion_flutter_xlsio: ^29.2.11  # إنشاء Excel
  mailer: ^6.0.1
  firebase_messaging: ^16.0.4
  package_info_plus: ^9.0.0  
  flutter_speed_dial: ^7.0.0
  flutter_local_notifications: ^19.5.0  
  # Firebase
  firebase_storage: ^13.0.3
  firebase_core: ^4.1.1
  firebase_auth: ^6.1.0
  cloud_firestore: ^6.0.0
  uuid: ^4.5.1
  #BLoC
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7
  # Custom Repository
  user_repository:
    path: packages/user_repository
  advertisement_repository:
    path: packages/advertisement_repository
  request_repository:
    path: packages/request_repository
  complaint_repository:
    path: packages/complaint_repository
  semester_repository:
    path: packages/semester_repository
  course_repository:
    path: packages/course_repository
  subjective_repository:
    path: packages/subjective_repository
  teacher_data_repository:
    path: packages/teacher_data_repository
  notification_repository:
    path: packages/notification_repository
  chat_repository:
    path: packages/chat_repository
  graduation_project_repository:
    path: packages/graduation_project_repository
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/animation/
    - assets/icons/

  fonts:
    - family: tajawal
      fonts:
        - asset: assets/fonts/ElMessiri-Regular.ttf
dependency_overrides:
  firebase_core: ^4.0.0
  firebase_auth: ^6.0.0
  cloud_firestore: ^6.0.0
 
 