name: chat_repository
description: Chat repository for Flutter application
publish_to: "none"
version: 1.0.0

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  uuid: ^4.5.1
  cloud_firestore: ^6.0.0
  equatable: ^2.0.7
  # Custom Repository
  user_repository:
    path: ../user_repository
  semester_repository: 
    path: ../semester_repository
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true